### ISSUE TITLE
Impossible to install Package

### ISSUE THREAD

**Issue by Pecana** [c4bo3l/crypto.aes#6]
Hello, even if I set my project to use Framework 2.0 when I try to install the nuget package I get the erorre message "The packages does not contains assembly reference"

**Comment by c4bo3l** [comment]
Hi Pecana,
Is it .Net Core 2.0?

Here is my test.
![image](https://user-images.githubusercontent.com/9482275/75445320-2b0af800-59a0-11ea-877e-14159e71094e.png)

I can install the package for the .Net Core 2.0 application.

**Comment by Pecana** [comment]
Ok with net core it works :-)

**Comment by c4bo3l** [comment]
If you want to use it for the regular .Net framework,, please read this website https://docs.microsoft.com/en-us/dotnet/standard/net-standard.
According to the website, you can use this library with .Net Framework 4.6.1.
